#version 460
#extension GL_EXT_ray_tracing : require

struct sphere 
{
    vec3 center;
    float radius;
    vec4 colour;
    uint normalColouring;
    uint materialIndex;
    uint padding[2];
};

layout(set = 0, binding = 6) buffer sphereBuffer {sphere s[];}spheres;

hitAttributeEXT vec2 attribs;

void main()
{
    sphere sph = spheres.s[gl_PrimitiveID];

    vec3 rayOrigin = gl_WorldRayOriginEXT;
    vec3 rayDir = gl_WorldRayDirectionEXT;

    vec3 oc = rayOrigin - sph.center;
    float b = dot(oc, rayDir);
    float c = dot(oc, oc) - sph.radius * sph.radius;
    float discriminant = b * b - c;

    if (discriminant > 0.0)
    {
        float sqrtD = sqrt(discriminant);

        float t1 = -b - sqrtD;
        if (t1 > 0.001)
        {
            reportIntersectionEXT(t1, 0);
            return;
        }

        float t2 = -b + sqrtD;
        if (t2 > 0.001)
        {
            reportIntersectionEXT(t2, 0);
            return;
        }
    }
}