#version 460
#extension GL_EXT_ray_tracing : require

const uint sphereShape = 0;
const uint quadShape = 1;

struct sphere 
{
    vec3 center;
    float radius;
    vec4 colour;
    uint normalColouring;
    uint textured;
    uint checkered;
    uint perlinNoise;
};

struct quad
{
    vec3 origin;
    float pad0; 
    vec3 edgeU;
    float pad1; 
    vec3 edgeV;
    float pad2; 
};

layout(set = 0, binding = 6) buffer sphereBuffer {sphere s[];}spheres;
layout(set = 0, binding = 8) buffer quadBuffer {quad q[];}quads;
layout(set = 0, binding = 9) buffer geoTypeBuffer {uint gt[];}geoTypes;

struct attributes
{
    vec2 uv;
};

hitAttributeEXT attributes attribs;


void sphereIntersection()
{
    sphere sph = spheres.s[gl_PrimitiveID];

    vec3 rayOrigin = gl_WorldRayOriginEXT;
    vec3 rayDir = gl_WorldRayDirectionEXT;

    vec3 oc = rayOrigin - sph.center;
    float b = dot(oc, rayDir);
    float c = dot(oc, oc) - sph.radius * sph.radius;
    float discriminant = b * b - c;

    if (discriminant > 0.0)
    {
        float sqrtD = sqrt(discriminant);

        float t1 = -b - sqrtD;
        if (t1 > 0.001)
        {

	    vec3 hitPoint = rayOrigin + t1 * rayDir;
	    vec3 p = (hitPoint - sph.center) / sph.radius;
	    
	    float u = 0.5 + atan(p.x, p.y) / (2.0 * 3.14159265359);
            float v = 0.5 - asin(p.z) / 3.14159265359;
	    attribs.uv = vec2(u, v);

            reportIntersectionEXT(t1, 0);
            return;
        }

        float t2 = -b + sqrtD;
        if (t2 > 0.001)
        {

   	    vec3 hitPoint = rayOrigin + t2 * rayDir;
	    vec3 p = (hitPoint - sph.center) / sph.radius;
	    
	    float u = 0.5 + atan(p.x, p.y) / (2.0 * 3.14159265359);
            float v = 0.5 - asin(p.z) / 3.14159265359;
	    attribs.uv = vec2(u, v);

            reportIntersectionEXT(t2, 0);
            return;
        }
    }
}

void quadIntersection()
{
    quad q = quads.q[gl_PrimitiveID];

    vec3 rayOrigin = gl_WorldRayOriginEXT;
    vec3 rayDir = gl_WorldRayDirectionEXT;

    vec3 normal = cross(q.edgeU, q.edgeV);
   
    float normLen = length(normal);
    if (normLen < 1e-6)
    {
        return;
    }

    normal = normal / normLen;

    float denom = dot(rayDir, normal);

    if (abs(denom) < 1e-6)
    {
        return;
    }

    float t = dot(q.origin - rayOrigin, normal) / denom;

    if (t < 0.001)
    {
        return;
    }

    vec3 p = rayOrigin + t * rayDir;
    vec3 local = p - q.origin;

    float u = dot(local, q.edgeU) / dot(q.edgeU, q.edgeU);
    float v = dot(local, q.edgeV) / dot(q.edgeV, q.edgeV);

    if (u >= -1e-5 && u <= 1.0 + 1e-5 && v >= -1e-5 && v <= 1.0 + 1e-5)
    {
        attribs.uv = vec2(u, v);
        reportIntersectionEXT(t, 0);
    }
}
void main()
{
    uint type = geoTypes.gt[gl_PrimitiveID];
    
    if(type == sphereShape)
    {
	sphereIntersection();
    }
    
    if(type == quadShape)
    {
	quadIntersection();
    }
}