#version 460

layout(set = 0, binding = 0, rgba8) writeonly uniform image2D outputImage;
layout(set = 0, binding = 1, rgba8) readonly uniform image2D inputImage;
layout(set = 0, binding = 2, rgba8) uniform image2D accumulationImage;

layout(push_constant) uniform PushConstants 
{
    uint frameIndex;
} pc;

vec3 toSRGB(vec3 linearColor) {
    return pow(clamp(linearColor, 0.0, 1.0), vec3(1.0/2.2));
}

void main()
{
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);

    vec4 newColour = imageLoad(inputImage, pixelCoords);

    newColour = vec4(newColour.b, newColour.g, newColour.r, newColour.a);

    vec4 accumulated;

    if (pc.frameIndex == 0) 
    {
        accumulated = newColour;
    }
    else
    {
        vec4 prevAccum = imageLoad(accumulationImage, pixelCoords);
        float N = float(pc.frameIndex);

        //average: prev * N + new / (N+1)
        accumulated = (prevAccum * N + newColour) / (N + 1.0);
    }

    
    imageStore(accumulationImage, pixelCoords, accumulated);
  
    vec3 gammaCorrected = toSRGB(accumulated.rgb);
    imageStore(outputImage, pixelCoords, vec4(gammaCorrected, 1.0));
}